### ISSUE TITLE
Any chance you could add installation details for MacOs

### ISSUE THREAD

**Issue by martisj** [nmklotas/GitLabCLI#7]
I'd love to check out this cli tool @nmklotas, however I don't know how to install it on MacOs?

**Comment by nmklotas** [comment]
Hi, I don't own Mac but for ubuntu and windows you only need to extract the zip file, here's the zip file for mac os https://github.com/nmklotas/GitLabCLI/releases/download/1.0.2/gitlabcli-osx-x64-v1.0.2.zip and run the executable from the command line: ./gitlab . Let me know if that works :)
